# Generated by Django 4.2.2 on 2024-03-06 11:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('items_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('registration_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255, verbose_name='Coupon Title')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('product_type', models.CharField(max_length=255, verbose_name='Product Type')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
                ('usd_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('exchange_type', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='user_profiles/')),
                ('name', models.CharField(help_text="User's name", max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the account was created')),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text="User's account status", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Refund', 'Refund')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_address', models.TextField()),
                ('billing_phone', models.CharField(max_length=15)),
                ('billing_tax_no', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('shipping_phone', models.CharField(max_length=15)),
                ('shipping_tax_no', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.company')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('web_url', models.URLField()),
                ('contact_email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('since_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_no', models.CharField(max_length=20, unique=True)),
                ('order_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pickups', 'Pickups'), ('Pending', 'Pending'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Out Of Delivery', 'Out Of Delivery')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Pending', 'Pending'), ('Denied', 'Denied')], max_length=10)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('transaction_type', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], max_length=4)),
                ('vat_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('payment_method', models.CharField(max_length=20)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('total_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.IntegerField()),
                ('orders', models.IntegerField(default=0)),
                ('colors', models.CharField(blank=True, max_length=255)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Scheduled', 'Scheduled')], default='Draft', max_length=10)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Hidden', 'Hidden')], default='Public', max_length=10)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category')),
            ],
        ),
    ]
